SET SERVEROUTPUT ON

DECLARE
    NUMBER1 NUMBER:=10;
    NUMBER2 NUMBER:=5;
    NUMBER3 CONSTANT NUMBER:= 7;
      NOMBRE VARCHAR2(10):= 'Kevin';
    EDAD NUMBER:=27;
   -- CUMPLE DATE:= 02-03-1996;
    
BEGIN

    DBMS_OUTPUT.PUT_LINE(NUMBER1 + NUMBER2 + NUMBER3);

END;
/

DECLARE
  
    NOMBRE VARCHAR2(10):= 'Kevin';
    EDAD NUMBER:=27;
    CUMPLE DATE:='02-03-1996';
   
BEGIN

    DBMS_OUTPUT.PUT_LINE(NOMBRE);
    DBMS_OUTPUT.PUT_LINE(EDAD);
    DBMS_OUTPUT.PUT_LINE(CUMPLE);
    DBMS_OUTPUT.PUT_LINE(NOMBRE||' '||EDAD||' '||CUMPLE);
    
END;   
/