SET SERVEROUTPUT ON;

DECLARE

    IMPUESTO CONSTANT NUMBER:=.21;
    PRODUCTO NUMBER(5,2);
    RESULTADO PRODUCTO%TYPE;

BEGIN
    PRODUCTO:=100.50;
    RESULTADO:=PRODUCTO+(PRODUCTO*IMPUESTO);
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;
/
